//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaAPI.App.Resources.Pages.DHCPv4Scopes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DHCPv4ScopeDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DHCPv4ScopeDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaAPI.App.Resources.Pages.DHCPv4Scopes.DHCPv4ScopeDisplay", typeof(DHCPv4ScopeDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept declines.
        /// </summary>
        public static string AcceptDecline {
            get {
                return ResourceManager.GetString("AcceptDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address allocation strategy.
        /// </summary>
        public static string AddressAllocationStrategy {
            get {
                return ResourceManager.GetString("AddressAllocationStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string AddressRangeEnd {
            get {
                return ResourceManager.GetString("AddressRangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string AddressRangeStart {
            get {
                return ResourceManager.GetString("AddressRangeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Addresses.
        /// </summary>
        public static string ExcludedAddresses {
            get {
                return ResourceManager.GetString("ExcludedAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has parent?.
        /// </summary>
        public static string HasParent {
            get {
                return ResourceManager.GetString("HasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept informs.
        /// </summary>
        public static string InformsAreAllowd {
            get {
                return ResourceManager.GetString("InformsAreAllowd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leasetime.
        /// </summary>
        public static string Leasetime {
            get {
                return ResourceManager.GetString("Leasetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Lifetime.
        /// </summary>
        public static string PreferredLifetime {
            get {
                return ResourceManager.GetString("PreferredLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal time.
        /// </summary>
        public static string RenewalTime {
            get {
                return ResourceManager.GetString("RenewalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver.
        /// </summary>
        public static string ResolverTypeName {
            get {
                return ResourceManager.GetString("ResolverTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse adress if possible.
        /// </summary>
        public static string ReuseAddressIfPossible {
            get {
                return ResourceManager.GetString("ReuseAddressIfPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string ScopePropertyOptionCode {
            get {
                return ResourceManager.GetString("ScopePropertyOptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ScopePropertyType {
            get {
                return ResourceManager.GetString("ScopePropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet mask.
        /// </summary>
        public static string SubnetmaskLength {
            get {
                return ResourceManager.GetString("SubnetmaskLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support direct unicast.
        /// </summary>
        public static string SupportDirectUnicast {
            get {
                return ResourceManager.GetString("SupportDirectUnicast", resourceCulture);
            }
        }
    }
}
