//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaAPI.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaAPI.App.Resources.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is invalid.
        /// </summary>
        public static string DHCPv6ScopePropertyValidation {
            get {
                return ResourceManager.GetString("DHCPv6ScopePropertyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is invalid.
        /// </summary>
        public static string DHCPv6ScopeResolverValuesViewModelValidation {
            get {
                return ResourceManager.GetString("DHCPv6ScopeResolverValuesViewModelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has to be greater than {1}.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid ipv6 address.
        /// </summary>
        public static string IPv6Address {
            get {
                return ResourceManager.GetString("IPv6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not in the range of the parent scope.
        /// </summary>
        public static string IPv6AddressInParentRange {
            get {
                return ResourceManager.GetString("IPv6AddressInParentRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address is not in range.
        /// </summary>
        public static string IPv6AdressInRange {
            get {
                return ResourceManager.GetString("IPv6AdressInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid subnet address.
        /// </summary>
        public static string IsIPv6Subnet {
            get {
                return ResourceManager.GetString("IsIPv6Subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already listed.
        /// </summary>
        public static string IsUniqueInCollection {
            get {
                return ResourceManager.GetString("IsUniqueInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too big. Maximum is {1}.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long. Maximum of {1} characters allowed.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too small. Minimum ist {1}.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short. At least {1} characters needed.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is invalid for the selected property.
        /// </summary>
        public static string NotificationPipelineActorProperty {
            get {
                return ResourceManager.GetString("NotificationPipelineActorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password are not the same.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not in parent scope range.
        /// </summary>
        public static string RebindTimeAdjustmentInParentRange {
            get {
                return ResourceManager.GetString("RebindTimeAdjustmentInParentRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add a value here.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not in parent scope range.
        /// </summary>
        public static string TimeSpanInParentRange {
            get {
                return ResourceManager.GetString("TimeSpanInParentRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too long. Value should be shorter than {1}.
        /// </summary>
        public static string TimeSpanMax {
            get {
                return ResourceManager.GetString("TimeSpanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short. Value should be longer than {1}.
        /// </summary>
        public static string TimeSpanMin {
            get {
                return ResourceManager.GetString("TimeSpanMin", resourceCulture);
            }
        }
    }
}
