// <auto-generated />
using System;
using DaAPI.Infrastructure.StorageEngine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DaAPI.Infrastructure.StorageEngine.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20200819104925_DHCPv6Statistics")]
    partial class DHCPv6Statistics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("DaAPI.Infrastructure.StorageEngine.DHCPv6.DHCPv6InterfaceDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterfaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DHCPv6Interfaces");
                });

            modelBuilder.Entity("DaAPI.Infrastructure.StorageEngine.DHCPv6.DHCPv6LeaseEntryDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<byte>("PrefixLength")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DHCPv6LeaseEntries");
                });

            modelBuilder.Entity("DaAPI.Infrastructure.StorageEngine.DHCPv6.DHCPv6PacketHandledEntryDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilteredBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HandledSuccessfully")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InvalidRequest")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RequestSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RequestType")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("ResponseSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("ResponseType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampDay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampMonth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampWeek")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DHCPv6PacketEntries");
                });

            modelBuilder.Entity("DaAPI.Infrastructure.StorageEngine.EventEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DaAPI.Infrastructure.StorageEngine.HelperEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Helper");
                });
#pragma warning restore 612, 618
        }
    }
}
